<a href="https://colab.research.google.com/github/prathikshaghasari/automotive-eda-python/blob/main/Project_Car_Dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Car Dataset Analysis

The **Car Dataset** provides detailed information on **11,914 U.S. vehicles** produced between **1990 and 2017**. Each entry represents a **unique vehicle configuration**, supporting analyses of **features, pricing, market trends**, and **fuel efficiency**.

## **Importing packages**

Python packages to cover data manipulation, visualization, and statistical analysis.

In [ ]:
# For numerical operations
import numpy as np

# For data manipulation and analysis
import pandas as pd

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# From drive
from google.colab import drive
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### **Data Loading**

Use Pandas to read CSV file format.

In [ ]:
# Load a CSV file
df_car = pd.read_csv ('/content/drive/MyDrive/Masterschool Project/Car_Dataset_Analysis.csv')
df_car.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

## **Understanding the Dataset**

**List of Columns in Dataframe**

In [ ]:
df_car.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

**Basic Inspection**

In [ ]:
# Column info of the dataset
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

**Summary Statistics**

In [ ]:
# Statistical summary for numerical columns
df_car.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

**Missing values**

In [ ]:
# Check for missing values
df_car.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

**Duplicate values**

In [ ]:
# Check if there are any duplicate rows
df_car.duplicated().sum()

# Show all duplicate rows
df_car[df_car.duplicated()]

Empty DataFrame
Columns: [Make, Model, Year, Engine Fuel Type, Engine HP, Engine Cylinders, Transmission Type, Driven_Wheels, Number of Doors, Market Category, Vehicle Size, Vehicle Style, highway MPG, city mpg, Popularity, MSRP]
Index: []

# **Project Tasks**

As part of this project, we are analyzing the dataset through three main tasks, each consisting of key subtasks:

**Data Cleaning**

*   Identifying and handling missing or inconsistent values
*   Standardizing formats and correcting data types

**Feature Engineering**

*   Creating new meaningful variables from existing data
*   Converting categorical variables and simplifying complex features

**Exploratory Data Analysis (EDA)**

*   Summarizing key statistics and distributions
*   Visualizing relationships between important features (e.g., price vs. horsepower, fuel type vs. MPG)
*   Detecting patterns, trends, and potential outliers

# **1. Data Cleaning**

### **1.1 Remove duplictes**

In [ ]:
df_car = df_car.drop_duplicates()

### **1.2 Handle Missing Data**

Rather than dropping the rows of **missing value** we can fill with the placeholder

In [ ]:
# Fill categorical with mode - for categorical columns
df_car['Engine Fuel Type'] = df_car['Engine Fuel Type'].fillna(df_car['Engine Fuel Type'].mode()[0])
df_car['Market Category'] = df_car['Market Category'].fillna('Unknown')

In [ ]:
# Fill numeric with mean or median - for numeric columns
df_car['Engine HP'] = df_car['Engine HP'].fillna(df['Engine HP'].mean())
df_car['Engine Cylinders'] = df_car['Engine Cylinders'].fillna(df_car['Engine Cylinders'].median())
df['Number of Doors'] = df_car['Number of Doors'].fillna(df_car['Number of Doors'].mode()[0])

In [ ]:
# Cofirm no missing values remain
print(df_car.isnull().sum())

Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Market Category      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

### **1.3 Data Type Conversion**

In [ ]:
# Convert numeric columns
df_car['Engine HP'] = df_car['Engine HP'].astype(float)
df_car['Engine Cylinders'] = df_car['Engine Cylinders'].astype(int)
df_car['Number of Doors'] = df_car['Number of Doors'].astype(int)
df_car['Year'] = df_car['Year'].astype(int)