<a href="https://colab.research.google.com/github/prathikshaghasari/automotive-eda-python/blob/main/Project_Car_Dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Car Dataset Analysis

The **Car Dataset** provides detailed information on **11,914 U.S. vehicles** produced between **1990 and 2017**. Each entry represents a **unique vehicle configuration**, supporting analyses of **features, pricing, market trends**, and **fuel efficiency**.

## **Importing packages**

Python packages to cover data manipulation, visualization, and statistical analysis.

In [1]:
# For numerical operations
import numpy as np

# For data manipulation and analysis
import pandas as pd

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# From drive
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

### **Data Loading**

Use Pandas to read CSV file format.

In [2]:
# Load a CSV file
df_car = pd.read_csv ('/content/drive/MyDrive/Masterschool Project/Car_Dataset_Analysis.csv')
df_car.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

## **Understanding the Dataset**

**List of Columns in Dataframe**

In [3]:
df_car.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

**Basic Inspection**

In [4]:
# Column info of the dataset
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

**Summary Statistics**

In [5]:
# Statistical summary for numerical columns
df_car.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

**Missing values**

In [6]:
# Check for missing values
df_car.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

**Duplicate values**

In [7]:
# Check if there are any duplicate rows
df_car.duplicated().sum()

# Show all duplicate rows
df_car[df_car.duplicated()]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

# **Project Tasks**

As part of this project, we are analyzing the dataset through three main tasks, each consisting of key subtasks:

**Data Cleaning**

*   Identifying and handling missing or inconsistent values
*   Standardizing formats and correcting data types

**Feature Engineering**

*   Creating new meaningful variables from existing data
*   Converting categorical variables and simplifying complex features

**Exploratory Data Analysis (EDA)**

*   Summarizing key statistics and distributions
*   Visualizing relationships between important features (e.g., price vs. horsepower, fuel type vs. MPG)
*   Detecting patterns, trends, and potential outliers

# **1. Data Cleaning**

### **1.1 Remove duplictes**

In [8]:
df_car = df_car.drop_duplicates()

### **1.2 Handle Missing Data**

Rather than dropping the rows of **missing value** we can fill with the placeholder

In [9]:
# Fill categorical with mode - for categorical columns
df_car['Engine Fuel Type'] = df_car['Engine Fuel Type'].fillna(df_car['Engine Fuel Type'].mode()[0])
df_car['Market Category'] = df_car['Market Category'].fillna('Unknown')

In [ ]:
# Fill numeric with mean or median - for numerical columns
df_car['Engine HP'] = df_car['Engine HP'].fillna(df_car['Engine HP'].mean())
df_car['Engine Cylinders'] = df_car['Engine Cylinders'].fillna(df_car['Engine Cylinders'].median())
df_car['Number of Doors'] = df_car['Number of Doors'].fillna(df_car['Number of Doors'].mode()[0])

In [15]:
# Cofirm no missing values remain
print(df_car.isnull().sum())

Make                  0
Model                 0
Year                  0
Engine Fuel Type      0
Engine HP            69
Engine Cylinders     30
Transmission Type     0
Driven_Wheels         0
Number of Doors       6
Market Category       0
Vehicle Size          0
Vehicle Style         0
highway MPG           0
city mpg              0
Popularity            0
MSRP                  0
dtype: int64

In [26]:
df_car.to_csv('project_car_dataset_cleaned_data')

### **1.3 Data Type Conversion**

Converting numeric columns to specific types like int or float ensures data consistency, memory efficiency, and correct analysis.

In [23]:
# Convert numeric columns
df_car['Engine HP'] = df_car['Engine HP'].astype(float)
df_car['Engine Cylinders'] = df_car['Engine Cylinders'].fillna(0).astype(int)
df_car['Number of Doors'] = df_car['Number of Doors'].fillna(0).astype(int)
df_car['Year'] = df_car['Year'].astype(int)

In [24]:
# Convert categorical columns
df_car['Market Category'] = df_car['Market Category'].astype('category')
df_car['Make'] = df_car['Make'].astype('category')
df_car['Model'] = df_car['Model'].astype('category')
df_car['Engine Fuel Type'] = df_car['Engine Fuel Type'].astype('category')

In [25]:
# Confirm changes
df_car.dtypes

Make                 category
Model                category
Year                    int64
Engine Fuel Type     category
Engine HP             float64
Engine Cylinders        int64
Transmission Type      object
Driven_Wheels          object
Number of Doors         int64
Market Category      category
Vehicle Size           object
Vehicle Style          object
highway MPG             int64
city mpg                int64
Popularity              int64
MSRP                    int64
dtype: object

### **1.4 Filtering Data**